import type { Role } from "@/lib/auth";

export const ROLES: readonly Role[] = ["user", "developer", "admin"];

export type ActionIntent = "neutral" | "primary" | "renewal" | "destructive";

/**
 * Triggers a client-side download of in-memory text generated by an admin
 * export without requiring a server-side artifact.
 */
export function downloadBlob(content: string, type: string, filename: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  try {
    document.body.appendChild(link);
    link.click();
  } finally {
    link.remove();
    URL.revokeObjectURL(url);
  }
}
